# Generated by Django 4.2.1 on 2023-05-18 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("educationalQualification", models.CharField(max_length=150)),
                ("yearsOfExperience", models.IntegerField()),
                ("workedInUber", models.BooleanField(default=False)),
                ("howLongWorkedInUber", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NextOfdKin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.EmailField(max_length=150)),
                ("dateOfBirth", models.DateField()),
                ("sex", models.CharField(max_length=150)),
                ("relationship", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=150)),
                ("phone_number_1", models.CharField(max_length=150)),
                ("phone_number_2", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beenArrested", models.BooleanField(default=False)),
                ("reasonForArrest", models.TextField()),
                ("beenBanned", models.BooleanField(default=False)),
                ("haveDebts", models.BooleanField(default=False)),
                ("registeredCredentials", models.TextField()),
                ("licenceNo", models.CharField(max_length=150)),
                ("expiryDate", models.DateField()),
                ("nin", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="BioData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateOfBirth", models.DateField()),
                ("sex", models.CharField(max_length=150)),
                ("marital_status", models.CharField(max_length=150)),
                ("state_of_origin", models.CharField(max_length=150)),
                ("phone_number_1", models.CharField(max_length=150)),
                ("phone_number_2", models.CharField(max_length=150)),
                ("lga", models.CharField(max_length=150)),
                ("village", models.CharField(max_length=150)),
                ("residential_state", models.CharField(max_length=150)),
                ("residential_address", models.CharField(max_length=150)),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.background",
                    ),
                ),
                (
                    "nextOfKin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.nextofdkin",
                    ),
                ),
                (
                    "securityQuestions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.securityquestions",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
