# Generated by Django 4.2.1 on 2023-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_background_nextofdkin_securityquestions_biodata"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="email",
            field=models.EmailField(default="dd", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="securityquestions",
            name="memberOfAnOrganization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="nextofdkin",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
