# Generated by Django 4.2.1 on 2023-05-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_biodata_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nextofdkin",
            name="email",
            field=models.EmailField(default="dd", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
