# Generated by Django 4.2.1 on 2023-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_nextofdkin_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityquestions",
            name="registeredCredentials",
            field=models.TextField(blank=True, null=True),
        ),
    ]
