# Generated by Django 4.2.1 on 2023-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_securityquestions_registeredcredentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofdkin",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
