# Generated by Django 4.2.1 on 2023-05-19 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_biodata_background_alter_biodata_nextofkin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUploadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_license",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("utility_bill", models.FileField(blank=True, null=True, upload_to="")),
                ("voter_id", models.FileField(blank=True, null=True, upload_to="")),
                ("face_shot", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
