# Generated by Django 4.2.1 on 2023-05-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_useruploaddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useruploaddata",
            name="driver_license",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/driver_licences"
            ),
        ),
        migrations.AlterField(
            model_name="useruploaddata",
            name="face_shot",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/driver_licences"
            ),
        ),
        migrations.AlterField(
            model_name="useruploaddata",
            name="utility_bill",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/driver_licences"
            ),
        ),
        migrations.AlterField(
            model_name="useruploaddata",
            name="voter_id",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/driver_licences"
            ),
        ),
    ]
