# Generated by Django 4.2.1 on 2023-05-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_useruploaddata_driver_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useruploaddata",
            name="face_shot",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/face_shots"
            ),
        ),
        migrations.AlterField(
            model_name="useruploaddata",
            name="utility_bill",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/utility_bills"
            ),
        ),
        migrations.AlterField(
            model_name="useruploaddata",
            name="voter_id",
            field=models.FileField(
                blank=True, null=True, upload_to="user_data/voter_ids"
            ),
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.EmailField(blank=True, max_length=254, null=True)),
                ("second", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
