# Generated by Django 4.2.1 on 2023-05-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_useruploaddata_face_shot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biodata",
            name="background",
        ),
        migrations.RemoveField(
            model_name="biodata",
            name="nextOfKin",
        ),
        migrations.RemoveField(
            model_name="biodata",
            name="securityQuestions",
        ),
        migrations.RemoveField(
            model_name="biodata",
            name="user",
        ),
        migrations.RemoveField(
            model_name="guarantor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useruploaddata",
            name="user",
        ),
        migrations.DeleteModel(
            name="Background",
        ),
        migrations.DeleteModel(
            name="BioData",
        ),
        migrations.DeleteModel(
            name="Guarantor",
        ),
        migrations.DeleteModel(
            name="NextOfdKin",
        ),
        migrations.DeleteModel(
            name="SecurityQuestions",
        ),
        migrations.DeleteModel(
            name="UserUploadData",
        ),
    ]
